// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/monachy/projek/internal/task (interfaces: LabelRepository)
//
// Generated by this command:
//
//	mockgen -destination internal/task/mock_label_repository.go -package task github.com/monachy/projek/internal/task LabelRepository
//

// Package task is a generated GoMock package.
package task

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockLabelRepository is a mock of LabelRepository interface.
type MockLabelRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLabelRepositoryMockRecorder
	isgomock struct{}
}

// MockLabelRepositoryMockRecorder is the mock recorder for MockLabelRepository.
type MockLabelRepositoryMockRecorder struct {
	mock *MockLabelRepository
}

// NewMockLabelRepository creates a new mock instance.
func NewMockLabelRepository(ctrl *gomock.Controller) *MockLabelRepository {
	mock := &MockLabelRepository{ctrl: ctrl}
	mock.recorder = &MockLabelRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLabelRepository) EXPECT() *MockLabelRepositoryMockRecorder {
	return m.recorder
}

// AddToTask mocks base method.
func (m *MockLabelRepository) AddToTask(ctx context.Context, taskID, labelID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToTask", ctx, taskID, labelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddToTask indicates an expected call of AddToTask.
func (mr *MockLabelRepositoryMockRecorder) AddToTask(ctx, taskID, labelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToTask", reflect.TypeOf((*MockLabelRepository)(nil).AddToTask), ctx, taskID, labelID)
}

// Create mocks base method.
func (m *MockLabelRepository) Create(ctx context.Context, label *Label) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, label)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLabelRepositoryMockRecorder) Create(ctx, label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLabelRepository)(nil).Create), ctx, label)
}

// Delete mocks base method.
func (m *MockLabelRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLabelRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLabelRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockLabelRepository) GetByID(ctx context.Context, id uuid.UUID) (*Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockLabelRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockLabelRepository)(nil).GetByID), ctx, id)
}

// GetByProject mocks base method.
func (m *MockLabelRepository) GetByProject(ctx context.Context, projectID uuid.UUID) ([]Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProject", ctx, projectID)
	ret0, _ := ret[0].([]Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProject indicates an expected call of GetByProject.
func (mr *MockLabelRepositoryMockRecorder) GetByProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProject", reflect.TypeOf((*MockLabelRepository)(nil).GetByProject), ctx, projectID)
}

// GetByTask mocks base method.
func (m *MockLabelRepository) GetByTask(ctx context.Context, taskID uuid.UUID) ([]Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTask", ctx, taskID)
	ret0, _ := ret[0].([]Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTask indicates an expected call of GetByTask.
func (mr *MockLabelRepositoryMockRecorder) GetByTask(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTask", reflect.TypeOf((*MockLabelRepository)(nil).GetByTask), ctx, taskID)
}

// RemoveFromTask mocks base method.
func (m *MockLabelRepository) RemoveFromTask(ctx context.Context, taskID, labelID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromTask", ctx, taskID, labelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromTask indicates an expected call of RemoveFromTask.
func (mr *MockLabelRepositoryMockRecorder) RemoveFromTask(ctx, taskID, labelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromTask", reflect.TypeOf((*MockLabelRepository)(nil).RemoveFromTask), ctx, taskID, labelID)
}

// Update mocks base method.
func (m *MockLabelRepository) Update(ctx context.Context, label *Label) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, label)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLabelRepositoryMockRecorder) Update(ctx, label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLabelRepository)(nil).Update), ctx, label)
}
