// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/monachy/projek/internal/project (interfaces: BoardRepository)
//
// Generated by this command:
//
//	mockgen -destination internal/project/mock_board_repository.go -package project github.com/monachy/projek/internal/project BoardRepository
//

// Package project is a generated GoMock package.
package project

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockBoardRepository is a mock of BoardRepository interface.
type MockBoardRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBoardRepositoryMockRecorder
	isgomock struct{}
}

// MockBoardRepositoryMockRecorder is the mock recorder for MockBoardRepository.
type MockBoardRepositoryMockRecorder struct {
	mock *MockBoardRepository
}

// NewMockBoardRepository creates a new mock instance.
func NewMockBoardRepository(ctrl *gomock.Controller) *MockBoardRepository {
	mock := &MockBoardRepository{ctrl: ctrl}
	mock.recorder = &MockBoardRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoardRepository) EXPECT() *MockBoardRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBoardRepository) Create(ctx context.Context, board *Board) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, board)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBoardRepositoryMockRecorder) Create(ctx, board any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBoardRepository)(nil).Create), ctx, board)
}

// Delete mocks base method.
func (m *MockBoardRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBoardRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBoardRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockBoardRepository) GetByID(ctx context.Context, id uuid.UUID) (*Board, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*Board)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBoardRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBoardRepository)(nil).GetByID), ctx, id)
}

// GetByProject mocks base method.
func (m *MockBoardRepository) GetByProject(ctx context.Context, projectID uuid.UUID) ([]Board, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProject", ctx, projectID)
	ret0, _ := ret[0].([]Board)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProject indicates an expected call of GetByProject.
func (mr *MockBoardRepositoryMockRecorder) GetByProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProject", reflect.TypeOf((*MockBoardRepository)(nil).GetByProject), ctx, projectID)
}

// Update mocks base method.
func (m *MockBoardRepository) Update(ctx context.Context, board *Board) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, board)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBoardRepositoryMockRecorder) Update(ctx, board any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBoardRepository)(nil).Update), ctx, board)
}
