// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/monachy/projek/internal/project (interfaces: EpicRepository)
//
// Generated by this command:
//
//	mockgen -destination internal/project/mock_epic_repository.go -package project github.com/monachy/projek/internal/project EpicRepository
//

// Package project is a generated GoMock package.
package project

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockEpicRepository is a mock of EpicRepository interface.
type MockEpicRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEpicRepositoryMockRecorder
	isgomock struct{}
}

// MockEpicRepositoryMockRecorder is the mock recorder for MockEpicRepository.
type MockEpicRepositoryMockRecorder struct {
	mock *MockEpicRepository
}

// NewMockEpicRepository creates a new mock instance.
func NewMockEpicRepository(ctrl *gomock.Controller) *MockEpicRepository {
	mock := &MockEpicRepository{ctrl: ctrl}
	mock.recorder = &MockEpicRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEpicRepository) EXPECT() *MockEpicRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEpicRepository) Create(ctx context.Context, epic *Epic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, epic)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEpicRepositoryMockRecorder) Create(ctx, epic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEpicRepository)(nil).Create), ctx, epic)
}

// Delete mocks base method.
func (m *MockEpicRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEpicRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEpicRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockEpicRepository) GetByID(ctx context.Context, id uuid.UUID) (*Epic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*Epic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEpicRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEpicRepository)(nil).GetByID), ctx, id)
}

// GetByProject mocks base method.
func (m *MockEpicRepository) GetByProject(ctx context.Context, projectID uuid.UUID) ([]Epic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProject", ctx, projectID)
	ret0, _ := ret[0].([]Epic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProject indicates an expected call of GetByProject.
func (mr *MockEpicRepositoryMockRecorder) GetByProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProject", reflect.TypeOf((*MockEpicRepository)(nil).GetByProject), ctx, projectID)
}

// Update mocks base method.
func (m *MockEpicRepository) Update(ctx context.Context, epic *Epic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, epic)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockEpicRepositoryMockRecorder) Update(ctx, epic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEpicRepository)(nil).Update), ctx, epic)
}
