// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/monachy/projek/internal/admin (interfaces: StatsRepository)
//
// Generated by this command:
//
//	mockgen -destination internal/admin/mock_stats_repository.go -package admin github.com/monachy/projek/internal/admin StatsRepository
//

// Package admin is a generated GoMock package.
package admin

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStatsRepository is a mock of StatsRepository interface.
type MockStatsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStatsRepositoryMockRecorder
	isgomock struct{}
}

// MockStatsRepositoryMockRecorder is the mock recorder for MockStatsRepository.
type MockStatsRepositoryMockRecorder struct {
	mock *MockStatsRepository
}

// NewMockStatsRepository creates a new mock instance.
func NewMockStatsRepository(ctrl *gomock.Controller) *MockStatsRepository {
	mock := &MockStatsRepository{ctrl: ctrl}
	mock.recorder = &MockStatsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsRepository) EXPECT() *MockStatsRepositoryMockRecorder {
	return m.recorder
}

// GetDashboardStats mocks base method.
func (m *MockStatsRepository) GetDashboardStats(ctx context.Context, communityID uuid.UUID) (*DashboardStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDashboardStats", ctx, communityID)
	ret0, _ := ret[0].(*DashboardStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDashboardStats indicates an expected call of GetDashboardStats.
func (mr *MockStatsRepositoryMockRecorder) GetDashboardStats(ctx, communityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDashboardStats", reflect.TypeOf((*MockStatsRepository)(nil).GetDashboardStats), ctx, communityID)
}
