// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/monachy/projek/internal/admin (interfaces: SettingsRepository)
//
// Generated by this command:
//
//	mockgen -destination internal/admin/mock_settings_repository.go -package admin github.com/monachy/projek/internal/admin SettingsRepository
//

// Package admin is a generated GoMock package.
package admin

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSettingsRepository is a mock of SettingsRepository interface.
type MockSettingsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsRepositoryMockRecorder
	isgomock struct{}
}

// MockSettingsRepositoryMockRecorder is the mock recorder for MockSettingsRepository.
type MockSettingsRepositoryMockRecorder struct {
	mock *MockSettingsRepository
}

// NewMockSettingsRepository creates a new mock instance.
func NewMockSettingsRepository(ctrl *gomock.Controller) *MockSettingsRepository {
	mock := &MockSettingsRepository{ctrl: ctrl}
	mock.recorder = &MockSettingsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingsRepository) EXPECT() *MockSettingsRepositoryMockRecorder {
	return m.recorder
}

// GetByCommunity mocks base method.
func (m *MockSettingsRepository) GetByCommunity(ctx context.Context, communityID uuid.UUID) (*CommunitySettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCommunity", ctx, communityID)
	ret0, _ := ret[0].(*CommunitySettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCommunity indicates an expected call of GetByCommunity.
func (mr *MockSettingsRepositoryMockRecorder) GetByCommunity(ctx, communityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCommunity", reflect.TypeOf((*MockSettingsRepository)(nil).GetByCommunity), ctx, communityID)
}

// Update mocks base method.
func (m *MockSettingsRepository) Update(ctx context.Context, settings *CommunitySettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSettingsRepositoryMockRecorder) Update(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSettingsRepository)(nil).Update), ctx, settings)
}
